### ISSUE TITLE
Neverending for loop in attenuation

### ISSUE THREAD

**Issue by AndrewSellek** [GiovanniPicogna/PLUTO4.4#3]
If the calculate_Attenuation in chemistry.c, the for loop to iterate over processors is missing "rank <" from its test expression, resulting in a neverending for loop since nprocs>=1 will always evaluate as true [https://github.com/GiovanniPicogna/PLUTO4.4/blob/main/Src/Chemistry/chemistry.c#L235](https://github.com/GiovanniPicogna/PLUTO4.4/blob/main/Src/Chemistry/chemistry.c#L235)

**Comment by GiovanniPicogna** [comment]
Yes, that was a mistake while pushing the commit.
Can you check that with the last commit the problem of parallelization has been solved for you?
I have added a Disk setup in Test_Problems/Chemistry/Disk and moved read_jflux to the init.c file

**Comment by GiovanniPicogna** [comment]
Issue solved by the last pull
